<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Victorias-Air.attlocal.net" ignored="0" name="Command line test" tests="3" failures="1" timestamp="10 Dec 2020 07:32:25 GMT" time="8.045" errors="0">
  <testcase name="sortWithCityAndName" time="6.807" classname="testPackage.SortTest"/>
  <testcase name="sortWithInvalid" time="0.433" classname="testPackage.SortTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [null] but found [io.restassured.internal.RestAssuredResponseImpl@4d6f623d]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [null] but found [io.restassured.internal.RestAssuredResponseImpl@4d6f623d]
at testPackage.SortTest.sortWithInvalid(SortTest.java:75)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- sortWithInvalid -->
  <testcase name="sortWithStateTypeAndName" time="0.765" classname="testPackage.SortTest"/>
</testsuite> <!-- Command line test -->
